import { existsSync, mkdirSync } from "node:fs";
import {
  intro,
  outro,
  text,
  confirm,
  note,
  spinner,
  cancel,
  isCancel,
  log,
} from "@clack/prompts";
import {
  validateTelegramToken,
  validateOwnerUserId,
  validateFolderPath,
  validateAiProvider,
} from "./validate.ts";
import { installSystemdService } from "./install.ts";

function exitIfCancelled<T>(value: T | symbol): asserts value is T {
  if (isCancel(value)) {
    cancel("Setup cancelled.");
    process.exit(0);
  }
}

intro("Rachel8 Setup");

note(
  "This wizard will configure Rachel8.\n" +
    "You'll need a Telegram bot token.\n" +
    "Choose Claude Code or Codex as the AI provider.\n" +
    "Have the selected app already installed and logged in on this server first.",
);

// 1. Telegram bot token
log.info(
  "Create a bot: open Telegram, message @BotFather, send /newbot,\n" +
    "follow the prompts, then copy the token.",
);

const telegramToken = await text({
  message: "Telegram bot token",
  placeholder: "123456789:ABCdef...",
  validate: validateTelegramToken,
});
exitIfCancelled(telegramToken);

// 2. Owner Telegram user ID
log.info(
  "Send /start to @userinfobot on Telegram to get your user ID.\n" +
    "This is a number like 123456789.",
);

const ownerUserId = await text({
  message: "Your Telegram user ID",
  placeholder: "123456789",
  validate: validateOwnerUserId,
});
exitIfCancelled(ownerUserId);

const aiProvider = await text({
  message: 'AI provider ("claudecode" or "codex")',
  placeholder: "codex",
  initialValue: "codex",
  validate: validateAiProvider,
});
exitIfCancelled(aiProvider);

if (aiProvider === "claudecode") {
  log.info("Before starting Rachel8, make sure Claude Code is logged in: claude login");
} else {
  log.info("Before starting Rachel8, make sure Codex is logged in: bun x codex login");
}

// 3. Shared folder path (auto-detect /data/shared/vault)
const defaultVaultPath = "/data/shared/vault";
const vaultExists = existsSync(defaultVaultPath);

if (vaultExists) {
  log.info(`Detected shared vault at ${defaultVaultPath}`);
}

const sharedFolder = await text({
  message: "Shared folder path",
  placeholder: "/data/shared/vault",
  initialValue: vaultExists ? defaultVaultPath : undefined,
  validate: validateFolderPath,
});
exitIfCancelled(sharedFolder);

// Check if the folder exists; offer to create it
if (!existsSync(sharedFolder)) {
  const shouldCreate = await confirm({
    message: `Folder ${sharedFolder} doesn't exist. Create it?`,
  });
  exitIfCancelled(shouldCreate);

  if (shouldCreate) {
    try {
      mkdirSync(sharedFolder, { recursive: true });
      log.success(`Created ${sharedFolder}`);
    } catch (err) {
      log.warn(`Could not create folder: ${err instanceof Error ? err.message : String(err)}`);
      log.warn("You may need to create it manually before starting Rachel.");
    }
  }
}

const s = spinner();
s.start("Writing configuration...");

const envContent = [
  "# Rachel8 Configuration (generated by setup wizard)",
  `TELEGRAM_BOT_TOKEN=${telegramToken}`,
  `OWNER_TELEGRAM_USER_ID=${ownerUserId}`,
  `AI_PROVIDER=${aiProvider}`,
  `SHARED_FOLDER_PATH=${sharedFolder}`,
  "NODE_ENV=production",
  "LOG_LEVEL=info",
].join("\n");

await Bun.write(".env", envContent + "\n");

s.stop("Configuration saved to .env");

const shouldInstallService = await confirm({
  message: "Install systemd service? (requires sudo)",
  initialValue: false,
});

if (!isCancel(shouldInstallService) && shouldInstallService) {
  const si = spinner();
  si.start("Installing systemd service...");
  try {
    await installSystemdService();
    si.stop("systemd service installed and started");
  } catch (err) {
    si.error(`Failed to install service: ${err instanceof Error ? err.message : String(err)}`);
    log.warn("You can install it later by re-running: bun run setup");
  }
} else {
  log.info("Skipped systemd service installation. You can install it later.");
}

outro(
  "Rachel8 is configured!\n\n" +
    "  Start: bun run start\n" +
    "  Dev:   bun run dev\n" +
    "  Logs:  sudo journalctl -u rachel8 -f",
);
