import { existsSync, mkdirSync } from "node:fs";
import {
  intro,
  outro,
  text,
  confirm,
  note,
  spinner,
  cancel,
  isCancel,
  log,
} from "@clack/prompts";
import {
  validateAnthropicKey,
  validateTelegramToken,
  validateExaKey,
  validateFolderPath,
} from "./validate.ts";
import { installSystemdService } from "./install.ts";

// ── Helpers ──────────────────────────────────────────────────────────────────

function handleCancel(value: unknown): asserts value is string {
  if (isCancel(value)) {
    cancel("Setup cancelled.");
    process.exit(0);
  }
}

// ── Wizard ───────────────────────────────────────────────────────────────────

intro("Rachel8 Setup");

note(
  "This wizard will configure Rachel8.\n" +
    "You'll need API keys from three services.\n" +
    "Each step includes instructions on where to get them.",
);

// 1. Anthropic API key
log.info("Get your API key from https://console.anthropic.com/settings/keys");

const anthropicKey = await text({
  message: "Claude API key",
  placeholder: "sk-ant-api03-...",
  validate: validateAnthropicKey,
});
handleCancel(anthropicKey);

// 2. Telegram bot token
log.info(
  "Create a bot: open Telegram, message @BotFather, send /newbot,\n" +
    "follow the prompts, then copy the token.",
);

const telegramToken = await text({
  message: "Telegram bot token",
  placeholder: "123456789:ABCdef...",
  validate: validateTelegramToken,
});
handleCancel(telegramToken);

// 3. Exa API key
log.info("Get your API key from https://dashboard.exa.ai/api-keys");

const exaKey = await text({
  message: "Exa API key",
  validate: validateExaKey,
});
handleCancel(exaKey);

// 4. Shared folder path (auto-detect /data/shared/vault)
const defaultVaultPath = "/data/shared/vault";
const vaultExists = existsSync(defaultVaultPath);

if (vaultExists) {
  log.info(`Detected shared vault at ${defaultVaultPath}`);
}

const sharedFolder = await text({
  message: "Shared folder path",
  placeholder: "/data/shared/vault",
  initialValue: vaultExists ? defaultVaultPath : undefined,
  validate: validateFolderPath,
});
handleCancel(sharedFolder);

// Check if the folder exists; offer to create it
if (!existsSync(sharedFolder)) {
  const shouldCreate = await confirm({
    message: `Folder ${sharedFolder} doesn't exist. Create it?`,
  });
  handleCancel(shouldCreate);

  if (shouldCreate) {
    try {
      mkdirSync(sharedFolder, { recursive: true });
      log.success(`Created ${sharedFolder}`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      log.warn(`Could not create folder: ${msg}`);
      log.warn("You may need to create it manually before starting Rachel.");
    }
  }
}

// ── Write .env ───────────────────────────────────────────────────────────────

const s = spinner();
s.start("Writing configuration...");

const envContent = [
  "# Rachel8 Configuration (generated by setup wizard)",
  `ANTHROPIC_API_KEY=${anthropicKey}`,
  `TELEGRAM_BOT_TOKEN=${telegramToken}`,
  `EXA_API_KEY=${exaKey}`,
  `SHARED_FOLDER_PATH=${sharedFolder}`,
  "NODE_ENV=production",
  "LOG_LEVEL=info",
].join("\n");

await Bun.write(".env", envContent + "\n");

s.stop("Configuration saved to .env");

// ── Install systemd service (optional) ───────────────────────────────────────

const shouldInstallService = await confirm({
  message: "Install systemd service? (requires sudo)",
  initialValue: false,
});

if (!isCancel(shouldInstallService) && shouldInstallService) {
  const si = spinner();
  si.start("Installing systemd service...");
  try {
    await installSystemdService();
    si.stop("systemd service installed and started");
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    si.error(`Failed to install service: ${msg}`);
    log.warn("You can install it later with: sudo cp rachel8.service /etc/systemd/system/");
  }
} else {
  log.info("Skipped systemd service installation. You can install it later.");
}

// ── Done ─────────────────────────────────────────────────────────────────────

outro(
  "Rachel8 is configured!\n\n" +
    "  Start: bun run start\n" +
    "  Dev:   bun run dev\n" +
    "  Logs:  sudo journalctl -u rachel8 -f",
);
